### PR TITLE
changed author order in bib

### PR DESCRIPTION
**Pull request by kushbhatia**
changed bib file as well to fix the error.

### CODE REVIEW

**Comment by alexandrebouchard** [comment]
The file to change is under _posts, the bib file gets regenerated from these md files. Please edit pull request.

**Comment by kushbhatia** [comment]
I had already made the required changes to the file in _posts directory and had added a new file by the name of "2019-05-24-abbasi-yadkori19a.md". However, this has resulted in the publication going off the MLR page. Can you let me know what changes would I be required to make to get it back on the webpage?

**Comment by alexandrebouchard** [comment]
After consultation, the name of the ids and files should NOT be changed. Please create a new pull request that use the updated author list but that do not change the ids and file names.

**Comment by kushbhatia** [comment]
Sure, I will close down this pull request and create a new one with only the requisite changes. Thanks!

**Pull request closed without merging**
